# A partir d'une image ubuntu 16.04
FROM ubuntu:16.04

# Installer les paquets suivants : 
RUN apt-get update && apt-get install -y bind9

COPY named.conf.local /etc/bind
COPY named.conf.default-zones /etc/bind
COPY db.wt3.ephec-ti.be /etc/bind
