# A partir d'une image ubuntu 16.04
FROM ubuntu:16.04

# Installer les paquets suivants : 
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential libxml2-dev libncurses5-dev linux-headers-`uname -r` libsqlite3-dev libssl-dev libedit-dev uuid-dev libjansson-dev \
	mkdir /usr/src/asterisk
	cd /usr/src/asterisk
	wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-16-current.tar.gz
	tar -xvzf asterisk-16-current.tar.gz
	cd asterisk-16.0.1                         # <--- Modifiez cette ligne en fonction de la version d'Asterisk
	./configure --with-jansson-bundled
	make menuselect
	--enable CORE-SOUNDS-FR-ULAW \
	--enable MOH-OPSOUND-ULAW \
	--enable EXTRA-SOUNDS-FR-ULAW \
	make && make install  && make samples && make config && \
	apt-get clean

# Copier tous les fichiers de config
COPY sip.conf /etc/asterisk
COPY users.conf /etc/asterisk
COPY extensions.conf /etc/asterisk

# Exposer les ports
EXPOSE 5060 5060/udp
EXPOSE 10000-20000/udp

CMD asterisk -rvvvv
